modLoader="javafml"
loaderVersion="[42,)"
license="ARR"

[[mods]]
modId="companion"
version="${file.jarVersion}"
displayName="Companion"
authors="Snownee"
displayURL="https://www.curseforge.com/minecraft/mc-mods/companion"
description="Protect your pets."

[[dependencies.companion]]
    modId="forge"
    mandatory=true
    versionRange="[42,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.companion]]
    modId="kiwi"
    mandatory=true
    versionRange="[8,)"
    ordering="NONE"
    side="BOTH"

[modproperties.companion]
    catalogueItemIcon="bone" #Support for Catalogue mod
